### PR TITLE
Remove whitespace, for new test

### PR DESCRIPTION
**Pull request by Waterdrips**
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

### CODE REVIEW

**Comment by Waterdrips** [comment]
Derek merge

**Comment by Waterdrips** [comment]
@alexellis what about a message from derek saying why he didn't merge? otherwise we question if he can hear us

**Comment by alexellis** [comment]
There are some there, others are in the logs. Work in progress. Messages are also rate limited.

**Comment by alexellis** [comment]
Burton isn't an approver in this repo

**Comment by Waterdrips** [comment]
> Burton isn't an approver in this repo

I assumed as much.

**Pull request merged**
